# Generated by Django 4.2 on 2024-11-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_user_full_name_alter_user_email_addr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_addr',
            field=models.EmailField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone_number',
            field=models.CharField(max_length=32),
        ),
    ]
